/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 41b1ff39a2a89bb8316ff4bbbe8c7848)
declare namespace Cloudflare {
	interface Env {
		VALUE_FROM_CLOUDFLARE: "Hello from Cloudflare" | "Hello from Cloudflare (Preview)";
		DB: D1Database;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VALUE_FROM_CLOUDFLARE">> {}
}
