/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b7a22fe4b675729da58b0665c7f96c6c)
declare namespace Cloudflare {
	interface Env {
		ENVIRONMENT: string;
		VALUE_FROM_CLOUDFLARE: string;
		DB: D1Database;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "VALUE_FROM_CLOUDFLARE">> {}
}
